version: "3"

services:
  web:
    container_name: "web"
    build: nginx
    ports:
      - "8081:80"
    volumes:
      - ./app/conf.d:/etc/nginx/conf.d
    networks:
      - network
    depends_on:
      - app

  app:
    container_name: "app"
    image: app
    environment:
      - MONGODB_URL=mongodb://mongo_db/database
    build: .
    ports:
      - "8000:8000"
    networks:
      - network
    depends_on:
      - mongo_db

  mongo_db:
      build: mongodb
      container_name: "mongo_db"
      ports:
        - "27017:27017"
      networks:
        - network

networks:
  network:
    driver: bridge
